language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r requirements_tests.txt
script:
  - python -m pytest
  - find batch_crop -name "*.py" | xargs pylint
  - find tests/src -name "*.py" | xargs pylint
  - python -m mypy batch_crop --ignore-missing-imports
after_success:
  - bash <(curl -s https://codecov.io/bash)
branches:
  only:
    - master
