language: python
python:
  - "3.6"
# command to install dependencies
script:
  - python -m pytest
  - find batch_crop -name *.py | xargs pylint
  - find tests/src -name *.py | xargs pylint
  - python -m mypy batch_crop --ignore-missing-imports
after_success:
  - bash <(curl -s https://codecov.io/bash)
branches:
  only:
    - master